name: 'Check Commits'
description: 'Checks that a minimum number of commits have been made'

outputs:
  num_commits:
    description: 'Number of commits found'
    value: ${{ steps.check_commits.outputs.num_commits }}

  min_commits:
    description: 'Minimum number of commits'
    value: ${{ steps.check_commits.outputs.min_commits }}

runs:
  # use composite and github-script instead of javascript so that 
  # do not have to maintain the node modules post-semester

  using: 'composite'
  steps:
    - id: check_commits
      uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        MIN_COMMITS: 6
      with:
        # using separate file for better syntax highlighting
        script: |
          const script = require(`${process.env.ACTION_PATH}/index.js`);
          return await script({core, exec});