name: 'Check Commits'
description: 'Checks that a minimum number of commits have been made'

runs:
  # use composite and github-script instead of javascript so that 
  # do not have to maintain the node modules post-semester

  using: 'composite'
  steps:
    - id: check_commits
      uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        MIN_COMMITS: 3
      with:
        # using separate file for better syntax highlighting
        script: |
          const script = require(`${process.env.ACTION_PATH}/index.js`);
          return await script({core, exec});