name: 'Setup Homework'
description: 'Setup environment for testing homework'

outputs:
  homework_name:
    description: 'Name of homework parsed from repository name'
    value: ${{ steps.parse_name.outputs.homework_name }}

  # found_commits:
  #   description: 'Number of commits found'
  #   value: ${{ steps.check_commits.outputs.path }}

  java_path:
    description: 'Path of Java installation'
    value: ${{ steps.setup_java.outputs.path }}

runs:
  using: 'composite'
  steps:
    - name: Parse homework name
      id: parse_name
      shell: bash
      run: |
        echo "Working: $(pwd)"
        echo "Repository: ${GITHUB_REPOSITORY}"

        if [[ ${GITHUB_REPOSITORY} =~ .+\/homework-([^-]+)-.+ ]]; then
          export HOMEWORK_NAME=${BASH_REMATCH[1]}
          echo "Homework Name: ${HOMEWORK_NAME}"
          echo "HOMEWORK_NAME=${HOMEWORK_NAME}" >> $GITHUB_ENV
          echo "homework_name=${HOMEWORK_NAME}" >> $GITHUB_OUTPUT
          echo ""
          exit 0
        fi

        echo "::error ::Repository ${GITHUB_REPOSITORY} in an unexpected format; cannot parse."

    # homework must be cloned into working directory
    # otherwise will break github classroom autograder

    - name: Clone homework repository
      uses: actions/checkout@v3

    - name: List homework files and commits
      shell: bash
      run: |
        echo "Listing homework files..."
        find . -not -path '*/.*' -type f
        echo ""

    # TODO: Move to grading step
    # # check number of commits in repository

    # - name: Check number of commits
    #   id: check_commits
    #   shell: bash
    #   run: |
    #     echo "Listing commits..."
    #     git fetch --unshallow
    #     NUM_COMMITS=$(git rev-list --count refs/remotes/origin/main)

    #     echo "NUM_COMMITS=${NUM_COMMITS}" >> $GITHUB_ENV
    #     echo "num_commits=${NUM_COMMITS}" >> $GITHUB_OUTPUT
    #     echo "Found ${NUM_COMMITS} commits."
    #     echo ""

    # get clean test files from template repository

    - name: Make temporary directory
      shell: bash
      run: |
        echo ""
        TEMPLATE_DIR=$(mktemp -d ~/template-XXXX)
        echo "Temporary Directory: ${TEMPLATE_DIR}"
        echo "TEMPLATE_DIR=${TEMPLATE_DIR}" >> $GITHUB_ENV

    - name: Checkout template repository
      shell: bash
      run: |
        TEMPLATE_REPO="https://github-actions:${{ github.token }}@github.com/${{ github.repository_owner }}/homework-${HOMEWORK_NAME}-template.git"
        git clone --depth 1 "${TEMPLATE_REPO}" ${TEMPLATE_DIR}/template

    - name: Setup clean test environment
      shell: bash
      run: |
        echo ""
        echo "Listing template files..."
        find ${TEMPLATE_DIR}/template -not -path '*/.*' -type f

        echo ""
        echo "Moving clean test files..."
        rm -rf src/test
        mv -fv ${TEMPLATE_DIR}/template/src/test src/
        mv -fv ${TEMPLATE_DIR}/template/pom.xml .
        
        echo ""
        echo "Listing clean test files..."
        find src/test/ -not -path '*/.*' -type f
        echo ""

    # setup java
    # https://github.com/actions/setup-java

    - name: Setup Java JDK 17
      id: setup_java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    # compile code (ignoring any warnings)
    - name: Compile homework and test code
      shell: bash
      run: |
        echo ""
        echo "Compiling homework..."
        mvn -f pom.xml -ntp --quiet "-Dconfig.xlint=-Xlint:none" "-Dconfig.xdoclint=-Xdoclint:none" "-Dconfig.werror=false" "-Dmaven.compiler.showWarnings=false" clean compile test-compile
        echo ""
