name: Homework Grade
description: Calculate homework grade with deductions and late penalties

inputs:
  grade_results:
    required: false
    type: string

  compile_status:
    required: false
    type: string

  javadoc_status:
    required: false
    type: string

  commits_status:
    required: false
    type: string

  num_commits:
    required: false
    type: string
  
  min_commits:
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - id: grade_homework
      uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        GRADE_RESULTS: ${{ inputs.grade_results }}
        COMPILE_STATUS: ${{ inputs.compile_status }}
        JAVADOC_STATUS: ${{ inputs.javadoc_status }}
        COMMITS_STATUS: ${{ inputs.commits_status }}
        NUM_COMMITS: ${{ inputs.num_commits }}
        MIN_COMMITS: ${{ inputs.min_commits }}

      with:
        script: |
          const script = require(`${process.env.ACTION_PATH}/index.js`);
          return await script({github, context, core});