name: Homework Grade
description: Calculate homework grade with deductions and late penalties

inputs:
  compile_status:
    required: false
    type: string

  javadoc_status:
    required: false
    type: string

  commits_status:
    required: false
    type: string

  # grade_results:
  #   required: false
  #   type: string

  # grade_starting:
  #   required: false
  #   type: string

  # grade_possible:
  #   required: false
  #   type: string

  # grade_points:
  #   required: false
  #   type: string

  # late_points:
  #   required: false
  #   type: string

  # late_multiplier:
  #   required: false
  #   type: string

runs:
  using: 'composite'
  steps:
    - id: grade_homework
      uses: actions/github-script@v6
      env:
        ACTION_PATH: "${{ github.action_path }}"
        COMPILE_STATUS: "${{ inputs.compile_status }}"
        JAVADOC_STATUS: "${{ inputs.javadoc_status }}"
        COMMITS_STATUS: "${{ inputs.commits_status }}"
        # GRADE_RESULTS: "{{ inputs.grade_results }}"
        # GRADE_STARTING: "${{ inputs.grade_starting }}"
        # GRADE_POSSIBLE: "${{ inputs.grade_possible }}"
        # GRADE_POINTS: "${{ inputs.grade_points }}"
        # LATE_POINTS: "${{ inputs.late_points }}"
        # LATE_MULTIPLIER: "${{ inputs.late_multiplier }}"

      with:
        script: |
          const script = require(`${process.env.ACTION_PATH}/index.js`);
          return await script({github, context, core});