name: Homework Grade
description: Calculate homework grade with deductions and late penalties

inputs:
  # assignment_name:
  #   required: false
  #   type: string

  grade_starting:
    required: false
    type: string

  # grade_possible:
  #   required: false
  #   type: string

  # compile_status:
  #   required: false
  #   type: string

  # javadoc_status:
  #   required: false
  #   type: string

  # commits_status:
  #   required: false
  #   type: string

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v6
      env:
        GRADE_STARTING: '${{ inputs.grade_starting }}'
      with:
        script: |
          const grade_starting = process.env.GRADE_STARTING;
          core.notice(`Earned ${grade_starting} from tests before any deductions`, {'title': `+${grade_starting} Points`});


