name: Homework Grade
description: Calculate homework grade with deductions and late penalties

inputs:
  grade_output:
    required: false
    type: string

  compile_status:
    required: false
    type: string

  javadoc_status:
    required: false
    type: string

  commits_status:
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - id: grade_homework
      uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        COMPILE_STATUS: ${{ inputs.compile_status }}
        JAVADOC_STATUS: ${{ inputs.javadoc_status }}
        COMMITS_STATUS: ${{ inputs.commits_status }}
        GRADE_OUTPUT: ${{ toJSON(inputs.grade_output) }}
      with:
        script: |
          const script = require(`${process.env.ACTION_PATH}/index.js`);
          return await script({github, context, core});