name: 'Late Homework'
description: 'Handle late homework grade issues'

inputs:
  known_users:
    description: 'Comma-separated list of known usernames'
    required: false

  artifact_name:
    description: 'Name of artifact'
    required: true

  artifact_json:
    description: 'Name of artifact JSON file'
    required: true

  workflow_name:
    description: 'Name of workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - id: parse_issue
      uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        KNOWN_USERS: ${{ inputs.known_users }}
      with:
        script: |
          const script = require(`${process.env.ACTION_PATH}/parse.js`);
          return await script({github, context, core});

    - id: check_results
      uses: usf-cs272-fall2023/cs272-bot/actions/check-results@main
      with:
        artifact_name: "${{ inputs.artifact_name }}"
        artifact_json: "${{ inputs.artifact_json }}"
        workflow_name: "${{ inputs.workflow_name }}"

    - uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        STUDENT_JSON: "${{ steps.parse_issue.outputs.result }}"
        RESULTS_JSON: "${{ steps.check_results.outputs.json_string }}"
      with:
        script: |
          const script = require(`${process.env.ACTION_PATH}/success.js`);
          return await script({github, context, core});