name: 'Late Homework'
description: 'Handle late homework grade issues'

inputs:
  access_token:
    description: 'Authentication token to access repositories'
    required: true
  artifact_name:
    description: 'Name of artifact'
    required: true
  artifact_json:
    description: 'Name of artifact JSON file'
    required: true
  workflow_name:
    description: 'Name of workflow'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "Not yet implemented"
        exit 1