name: 'Check Results'
description: 'Checks for (and returns) JSON results stored as a workflow artifact.'

inputs:
  access_token:
    description: 'Authentication token to access repositories'
    required: true
  artifact_name:
    description: 'Name of artifact'
    required: true
  artifact_json:
    description: 'Name of artifact JSON file'
    required: true
  workflow_name:
    description: 'Name of workflow'
    required: true
  workflow_run:
    description: 'Run ID of workflow'
    required: false

outputs:
  json_string:
    description: 'JSON file encoded as a string'

runs:
  # use composite and github-script instead of javascript so that 
  # do not have to maintain the node modules post-semester

  using: 'composite'
  steps:
    - shell: bash
      run: npm install node-fetch

    - shell: bash
      run: npm install adm-zip

    - id: check_results
      uses: actions/github-script@v6
      env:
        ACTION_PATH: ${{ github.action_path }}
        ARTIFACT_NAME: "${{ inputs.artifact_name }}"
        ARTIFACT_JSON: "${{ inputs.artifact_json }}"
        WORKFLOW_NAME: "${{ inputs.workflow_name }}"
        WORKFLOW_RUN:  "${{ inputs.workflow_run }}"
      with:
        # using separate file for better syntax highlighting
        script: |
          const fetch = require('node-fetch');
          const AdmZip = require("adm-zip");
          const script = require(`${process.env.ACTION_PATH}/index.js`);
          return await script({github, context, core, fetch, AdmZip});