name: Homework Grade

on:
  workflow_call:

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      homework_name: ${{ steps.homework_setup.outputs.homework_name }}
      java_path: ${{ steps.homework_setup.outputs.homework_name }}
      points: ${{ steps.autograder.outputs.points }}
      autograder: ${{ steps.autograder.outcome }}

    steps:
      - name: Setup homework environment
        id: homework_setup
        uses: usf-cs272-fall2023/cs272-bot/actions/homework-setup@main

      - name: Run GitHub autograder
        id: autograder
        uses: education/autograding@v1

  grade:
    name: Grade
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test
    if: ${{ !cancelled() && (needs.test.outputs.autograder == 'success' || needs.test.outputs.autograder == 'failure') }}

    steps:
      - name: Output autograder results
        uses: actions/github-script@v6
        with:
          script: |
            const outputs = ${{ toJSON(needs.test.outputs) }};
            for (const property in outputs) {
              core.info(`${propery}: ${outputs[property]}`);
            }

      - name: Parse grade output
        uses: actions/github-script@v6
        with:
          script: |
            core.info('hello');

        #   env:
        #   HOMEWORK_NAME: ${{ needs.test.outputs.homework_name }}
        #   JAVA_PATH: ${{ needs.test.outputs.java_path }}
        #   POINTS: ${{ needs.test.outputs.points }}
        #   AUTOGRADER: ${{ needs.test.outputs.autograder }}
        # shell: bash
        # run: |
        #   echo "  Homework: ${HOMEWORK_NAME}"
        #   echo " Java Path: ${JAVA_PATH}"
        #   echo "    Points: ${POINTS}"
        #   echo "Autograder: ${AUTOGRADER}"


    # TODO: Add checking commits, warnings, deadline to grade job, add badge