name: 'Project Stats'

on:
  workflow_call:

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Listing issues'
        uses: actions/github-script@v6
        with:
          script: |
            const config = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            };

            const [grade_tests, grade_design] = await Promise.all([
              github.rest.issues.listForRepo({
                ...config,
                labels: 'grade-tests'
              }),
              github.rest.issues.listForRepo({
                ...config,
                labels: 'grade-design'
              })
            ]);

            core.info(grade_tests?.data?.length);
            core.info(grade_design?.data?.length);
            

      # - name: 'Install cloc'
      #   run: |
      #     sudo apt install cloc
      #     cloc --version

      # compare project 1.1 test to 1.x design
      # compare 2.1 test to 2.x design
      # compare 3.1 test to 3.x design

      # compare 1.x design to current version of code