name: 'Project Stats'

on:
  workflow_call:

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout scripts'
        id: checkout_workflows
        uses: actions/checkout@v4
        with:
          repository: usf-cs272-fall2023/cs272-bot
          sparse-checkout: .github/scripts
          path: 'scripts'

      - name: 'Download issues'
        id: download_issues
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./scripts/repo-issues.js');
            return await script({github, context, core});

      # - name: 'Install cloc'
      #   run: |
      #     sudo apt install cloc
      #     cloc --version

      # compare project 1.1 test to 1.x design
      # compare 2.1 test to 2.x design
      # compare 3.1 test to 3.x design

      # compare 1.x design to current version of code