name: 'Project Stats'

on:
  workflow_call:

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Listing issues'
        uses: actions/github-script@v6
        with:
          script: |
            const config = {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            };

            const project1 = await github.rest.issues.listForRepo({
              ...config,
              labels: 'project1'
            });

            core.info(JSON.stringify(project1));

      # - name: 'Install cloc'
      #   run: |
      #     sudo apt install cloc
      #     cloc --version

      # compare project 1.1 test to 1.x design
      # compare 2.1 test to 2.x design
      # compare 3.1 test to 3.x design

      # compare 1.x design to current version of code