name: 'Project Stats'

on:
  workflow_call:
    inputs:
      action_ref:
        description: "Ref for workflow or action checkout"
        required: false
        default: 'main'
        type: string

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest
    if: ${{ contains(fromJson('["sjengle"]'), github.event.review.user.login) }}

    steps:
      - name: 'Install cloc'
        run: |
          sudo apt install cloc
          cloc --version
