name: 'Project Stats'

on:
  workflow_call:

jobs:
  main:
    name: 'Main'
    runs-on: ubuntu-latest

    steps:
      - name: 'Install cloc'
        run: |
          sudo apt install cloc
          cloc --version
